version: '3.1'

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./src:/usr/app/src
    depends_on:
      - postgres
      - redis
    command: npm run dev

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

volumes:
  postgres-data:
